# Generated by Django 3.1.1 on 2021-10-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='short_text',
            field=models.TextField(blank=True, default=False, max_length=1000, null=True),
        ),
    ]
